[Nginx]
Nginx ansible_host=172.31.2.9 ansible_ssh_user='ubuntu'

[tooling]
web1 ansible_host=172.31.2.109 ansible_ssh_user='ec2-user'
web2 ansible_host=172.31.2.111 ansible_ssh_user='ec2-user'

# [todo]
# <Todo-web-server-private-IP-Address>

# [db:vars]
# ansible_user=ec2-user
# ansible_python_interpreter=/usr/bin/python

[db]
Database ansible_host=172.31.2.188 ansible_ssh_user='ec2-user'
