pipeline {
    agent any

    environment {
        WORKSPACE = "${env.WORKSPACE}" // Workspace variable
    }

    stages {
        stage('Checkout SCM') {
            steps {
                git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/Dreyshantel/ansible-config-mgt.git'
            }
        }

        stage('Initial Cleanup') {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir() // Cleanup the workspace
                }
            }
        }

        stage('Prepare Ansible For Execution') {
            steps {
                sh '''
                echo "Listing deploy directory contents:"
                ls -la ${WORKSPACE}/deploy
                if [ -f "${WORKSPACE}/deploy/ansible.cfg" ]; then
                    sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg
                else
                    echo "ansible.cfg not found, skipping sed command"
                fi
                '''
            }
        }

        stage('Test SSH Connections') {
            steps {
                script {
                    def allHosts = [
                        'ubuntu@172.31.89.253',
                        'ubuntu@172.31.91.227',
                        'ec2-user@172.31.81.236',
                        'ec2-user@172.31.85.118'
                    ]
                    
                    sshagent(['your-correct-credential-id']) {
                        allHosts.each { host ->
                            sh """
                                ssh -o StrictHostKeyChecking=no ${host} exit || echo "Failed to connect to ${host}, continuing..."
                            """
                        }
                    }
                }
            }
        }

        stage('Run Ansible playbook') {
            when {
                expression { fileExists("${WORKSPACE}/deploy/ansible.cfg") }
            }
            steps {
                sh '''
                ansible-playbook -i inventory playbook.yml
                '''
            }
        }
    }

    post {
        always {
            cleanWs() // Clean up the workspace after execution
        }
    }
}
